include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 100

analyzer:
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore
    unused_element: ignore

custom_lint:
  rules:
    - avoid_manual_providers_as_generated_provider_dependency: false
