name: spendit
description: "Spend It adalah sebuah aplikasi pengelola keuangan pribadi yang dirancang khusus untuk membantu Anda mengelola keuangan Anda dengan lebih baik. Dengan Spend It, Anda dapat dengan mudah mengelola keuangan Anda, termasuk pemasukan dan pengeluaran, serta melihat laporan keuangan Anda secara detail."
publish_to: "none"
version: 2.0.0

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.4.1
  device_info_plus: ^12.1.0
  flutter:
    sdk: flutter
  flutter_gen: ^5.12.0
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^3.0.1
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  go_router: ^16.2.4
  hugeicons: ^1.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  path: ^1.9.1
  reactive_forms: ^18.1.1
  riverpod_annotation: ^3.0.1
  riverpod_sqflite: ^0.3.1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  syncfusion_flutter_charts: ^31.1.22
  thing_toast: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_gen_runner: ^5.12.0
  riverpod_generator: ^3.0.1
  build_runner: ^2.7.1
  go_router_builder: ^4.1.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  riverpod_lint: ^3.0.1
  custom_lint: ^0.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-Bold.ttf
          weight: 700
        - asset: fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: fonts/Manrope-Medium.ttf
          weight: 500
        - asset: fonts/Manrope-Regular.ttf
          weight: 400

flutter_native_splash:
  android: true
  ios: false
  color: "#1E1E2E"
  image: assets/icons/splash.png
  android_12:
    color: "#1E1E2E"
    image: assets/icons/splash-android12.png

flutter_gen:
  output: lib/src/core/gen
  parse_metadata: true
