name: spendit
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  fpdart: ^1.1.1
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  json_annotation: ^4.9.0
  go_router: ^14.8.0
  reactive_forms: ^17.0.1
  gap: ^3.0.1
  uuid: ^4.5.1
  solar_icons: ^0.0.5
  sqflite: ^2.4.2
  path: ^1.9.1
  native_storage: ^0.2.2
  fl_chart: ^0.70.2
  flex_color_scheme: ^8.1.1
  animations: ^2.0.11
  flutter_animate: ^4.5.2
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  skeletonizer: ^1.4.3
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.4
  json_serializable: ^6.9.4
  freezed: ^2.5.8
  custom_lint: ^0.7.3
  riverpod_lint: ^2.6.4
  flutter_native_splash: ^2.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - shorebird.yaml
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: fonts/SF-Pro-Display-Light.otf
          weight: 300
    - family: SF Pro Text
      fonts:
        - asset: fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: fonts/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: fonts/SF-Pro-Text-Light.otf
          weight: 300
