name: spendit_core
description: "Spend It app UI and Service package."
version: 0.1.0
# homepage:

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  iconsax_plus: ^1.0.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  reactive_forms: ^18.1.1
  talker_logger: ^4.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  build_runner: ^2.7.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
# flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: SpendItIcons
  #     fonts:
  #       - asset: fonts/iconsax.ttf
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
