include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  plugins:
    - custom_lint

custom_lint:
  rules:
    - avoid_manual_providers_as_generated_provider_dependency: false
