include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  errors:
    invalid_annotation_target: ignore
    override_on_non_overriding_member: ignore
  plugins:
    - custom_lint

custom_lint:
  rules:
    - avoid_manual_providers_as_generated_provider_dependency: false
