name: spendit
description: "Spend It adalah sebuah aplikasi pengelola keuangan pribadi yang dirancang khusus untuk membantu Anda mengelola keuangan Anda dengan lebih baik. Dengan Spend It, Anda dapat dengan mudah mengelola keuangan Anda, termasuk pemasukan dan pengeluaran, serta melihat laporan keuangan Anda secara detail."
publish_to: "none"
version: 2.0.0

environment:
  sdk: ^3.8.0

dependencies:
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_gen: ^5.10.0
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  go_router: ^16.0.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  native_storage: ^0.3.0
  path: ^1.9.1
  reactive_dropdown_search: ^6.0.0-pre4
  reactive_forms: ^18.1.1
  riverpod_annotation: ^2.6.1
  skeletonizer: ^2.1.0
  spendit_core: 0.0.1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  freezed: ^3.1.0
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  json_serializable: ^6.9.5
  riverpod_lint: ^2.6.5
  flutter_gen_runner: ^5.10.0
  flutter_native_splash: ^2.4.6
  mocktail: ^1.0.4
  go_router_builder: ^3.0.0
  build_verify: ^3.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Figtree
      fonts:
        - asset: fonts/Figtree-Bold.ttf
          weight: 700
        - asset: fonts/Figtree-SemiBold.ttf
          weight: 600
        - asset: fonts/Figtree-Medium.ttf
          weight: 500
        - asset: fonts/Figtree-Regular.ttf
          weight: 400
        - asset: fonts/Figtree-Light.ttf
          weight: 300
