name: spendit_remake
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_gen: ^5.10.0
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  gap: ^3.0.1
  go_router: ^15.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  native_storage: ^0.2.3
  path: ^1.9.1
  reactive_dropdown_search: ^5.0.6
  reactive_forms: ^17.0.0
  reactive_forms_annotations: ^6.0.0
  riverpod_annotation: ^2.6.1
  skeletonizer: ^1.4.3
  solar_icons: ^0.0.5
  spendit_core: 0.0.1
  sqflite: ^2.4.2
  talker_logger: ^4.7.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  json_serializable: ^6.9.5
  riverpod_lint: ^2.6.5
  flutter_gen_runner: ^5.10.0
  flutter_native_splash: ^2.4.6
  reactive_forms_generator: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Figtree
      fonts:
        - asset: fonts/Figtree-Bold.ttf
          weight: 700
        - asset: fonts/Figtree-SemiBold.ttf
          weight: 600
        - asset: fonts/Figtree-Medium.ttf
          weight: 500
        - asset: fonts/Figtree-Regular.ttf
          weight: 400
        - asset: fonts/Figtree-Light.ttf
          weight: 300
    - family: Geist
      fonts:
        - asset: fonts/Geist-Bold.ttf
          weight: 700
        - asset: fonts/Geist-SemiBold.ttf
          weight: 600
        - asset: fonts/Geist-Medium.ttf
          weight: 500
        - asset: fonts/Geist-Regular.ttf
          weight: 400
        - asset: fonts/Geist-Light.ttf
          weight: 300
